### ISSUE TITLE
Rename app

### ISSUE THREAD

**Issue by dschuermann** [SufficientlySecure/calendar-import-export#24]
I would propose renaming the app to "ICS Import/Export"  to prevent name conflict with the original (now closed source) version of this app on Google Play.

**Comment by Gitoffthelawn** [comment]
In order to increase search visibility, I would recommend including the word "Calendar".  Perhaps "Calendar (ICS) Import/Export".

**Comment by dschuermann** [comment]
Hm good idea.
If we concentrate on the main functionality of importing/exporting whole calendars we could also name it "Calendar Backup & Restore (ICS, iCal)" or "Calendar Import/Export (ICS, iCal)"
@Gitoffthelawn What do you think? I currently prefer Backup & Restore...

**Comment by dschuermann** [comment]
Maybe "Import/Export" is not that bad considering the scenario someone exports a calendar from a cloud provider to an ics file and then searches on Google Play for "import calendar" or "import ics"

**Comment by Gitoffthelawn** [comment]
It's a tough call since "import/export" and "backup/restore" are often used interchangeably.  Ideally, the app name would have both sets of terms, but that would be unwieldy.

A workable solution is to use one set of terms in the app name and both sets in the description.  That way, search visibility is maximized while keeping a reasonable app name.

Give me a little time to think about whether "import/export" or "backup/restore" is more suitable.

Off the cuff, I think "import/export" will cater to a more technical crowd, whereas "backup/restore" will favor a less technical one.

Of course, we are just speaking about English.  Are app names translated to other languages, or do they keep their same names regardless of language?

**Comment by Gitoffthelawn** [comment]
Another word to include in the description is "offline".  It should not be in the app name, since the app works for both online and offline calendars, but given that you have received many requests from users of your "Offline Calendar" app, it will be an important word to include.

**Comment by dschuermann** [comment]
Scenarios to consider:
1) Someone wants to backup her calendars from Offline Calendar. She goes into Offline Calender and is promted to install this app -> check
2) Someone wants to migrate her calender from Thunderbird's Lightning. She goes into Thunderbird clicks right on the calendar and selects "Export Calendar…". She will then search for "import calendar" in Google Play. -> + for "Calendar Import/Export"
3) Someone wants to backup some other calendars. She will search for "backup calendar" -> + for "Calendar Backup/Restore".

I think scenario 3 is rare, most people only backup with scenario 1. Also I don't think someone would search for "restore calendar", the word restore is not used alone normally, while the word import is.

I vote for "Calendar Import/Export (ics, iCal)"

**Comment by Gitoffthelawn** [comment]
I'm definitely leaning in the same direction: *Calendar Import/Export (ics, iCal)*

**Comment by jgriffiths** [comment]
I am in situation (3), I admit I am probably an outlier though :-)

iCal is the old calendar application name. The format is called iCalendar. Google Play policy frowns on starting an app name with another app or product name, even though iCal is now defunct, the proscription makes sense to me.

I also think (ics, iCal) reads poorly in the name and looks like keyword stuffing/spam. It would be better and more natural to list the file type support ("ics, also known as iCal or iCalendar") alongside the input/output methods ("Export to local file, Import from file, website or ftp site") in the description.

The name itself should describe what the app does as well as being easily searchable. I think that iCalendar will match in searches for both 'calendar' and 'iCal', so an accurate name that describes the functionality would be something like:

"iCalendar Import, Export and Backup"

Any search including (icalendar, calendar, ical) and (Import, Export, Backup) will find the app easily. Note that "Restore" need not be given in a name as it is implied (see e.g. Titanium Backup).

Thoughts?

**Comment by dschuermann** [comment]
I like your suggestion to include "Import, Export and Backup" in the name. Unfortunately, we have only 30 characters maximum. Including "iCalendar" sounds like an Apple product to be honest :grimacing: 
So to keep under 30 characters I am currently for "Calendar Import/Export (ics)". I prefer to include ics instead of iCal because when you export from Thunderbird the file is an ics file (no mention of ical). Also on Google Calendar's web interface, when you export the calendar, you get ics files inside a zip (that is named "x.ical.zip", but you need to extract it before we could import it).

**Comment by jgriffiths** [comment]
Ah yeah, 30 character limit, bummer. My final suggestion would then be "Calendar Import/Export/Backup" as I don't think having iCal or ics in the name is useful compared to the description.

However, I'm not too fussed about this. People will find the app easily enough I think.

**Comment by Gitoffthelawn** [comment]
I like @jgriffiths point that the term *Restore* is the least important.

I also agree with @dschuermann that using *iCalendar* makes it sound like an Apple product.

The name *Calendar Import/Export/Backup* would likely provide good search visibility; on the other hand, it seems a bit convoluted with the inclusion of both *Export* and *Backup*.

I think we all agree that the word *Calendar* should be present, and it seems like everyone is leaning towards including *Import/Export*.

Given the 30 character limit imposed by Google, I think the decision is between including the word *Backup* or the terms *ics, iCal*.  I think both are good, and there isn't a wrong decision.

Personally, I think I would find an app with the term *ics* in the name faster, because if I have an .ics file that I want to import, then that's going to be a search term.  On the other hand, I think many people will search for the more common term *Backup*.  If the goal is to attract a more technical crowd, then I recommend including *ics, iCal*; if the goal is to attract a more general crowd, then I recommend including *Backup*.

**Comment by jgriffiths** [comment]
This repo is now ranked fifth when searching google for "ical import export". A few links here to the play store app (or at least one in README.md) would be a good idea. I don't think visibility through searches is going to be an issue.

The link https://android.stackexchange.com/questions/25210/how-to-backup-the-android-calendar-file-is-there-such-a-file is also a first page result for that search and is begging for an answer pointing to this fork and its play store link.

**Comment by dschuermann** [comment]
Final renaming done:
* It is named "calendar-import-export" everywhere as the URL path
* "Calendar Import/Export" as the app name inside the apk and everywhere else
* On Google Play: "Calendar Import/Export (ics)"

I think this is a good tradeoff :)
