### ISSUE TITLE
[bug?] Export files contain extraneous data

### ISSUE THREAD

**Issue by Gitoffthelawn** [SufficientlySecure/calendar-import-export#40]
The beginning of export files contain scores of `RDATE` lines as well as multiple `DTSTART` sections.

I think some of this data (most likely the multiple `DTSTART` sections) is due to every time in history DST has been modified.  But the weird thing is that there are separate RDATE lines for scores of years, beginning roughly 100 years ago.  DST changes are much less frequent than that.

I'm not sure if this is a bug, but it's definitely odd.

**Comment by jgriffiths** [comment]
Can you attach an example export file containing this possibly extraneous data? Feel free to change any privacy sensitive fields.

Also whether you have timezone updates enabled in preferences would be useful to know.

**Comment by Gitoffthelawn** [comment]
@jgriffiths Yes, I can get that data.  It will take a little time due to the device being repaired.

If you can, try making a few exports, and see if you get the same thing (it's pretty obvious... scored of `RDATE` lines near the top of the file).  If you don't, then me getting you the data will be the only way.  Well, unless someone else has the same issue and uploads an example.

**Comment by jgriffiths** [comment]
The data exported here is just the representation of the timezone, which includes all previous updates to it throughout history. The RDATE sections are either present because a tool generates the timezone definitions or an RRULE is not flexible enough to represent the changes.

Given that the presence of the timezone helps interop and there are as-yet no complaints about importing the resulting .ics in other tools, I think this is a non-bug.
